micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:mysql://localhost:3306/demo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: demo
    password: 'password'
#    schema-generate: CREATE_DROP
    dialect: MYSQL

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:dbscripts