micronaut:
  application:
    name: demo
datasources:
  default:
    url: jdbc:mysql://${db.host:localhost}:${db.port:3306}/${db.schema:demo}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${db.user:demo}
    password: ${db.password:password}
#    schema-generate: CREATE_DROP
    dialect: MYSQL

flyway:
  datasources:
    default:
      enabled: true
      locations:
        - classpath:dbscripts